Pokemon_Traker_Site/Pokemon_Traker_Site/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^pokemon/', include('pokemon.urls', namespace="pokemon")),
    url(r'^tracker/', include('tracker.urls', namespace="tracker")),
]

Pokemon_Traker_Site/pokemon/urls.py
from django.conf.urls import url
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^$', views.markPokemon, name='markPokemon'),
    url(r'^(?P<pokemonId>\d+)/$', views.showPokemon, name='showPokemon'),
    url(r'delete/$', views.deletePokemon, name='deletePokemon'),
    url(r'deleteOld/$', views.deleteTooOldPokemon, name='deleteTooOldPokemon'),
]

Pokemon_Traker_Site/tracker/urls.py
from django.conf.urls import url
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^(?P<pokemonId>\d+)/$', views.tracker, name='tracker'),
]

Pokemon_Traker_Site/pokemon/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Pokemon(models.Model):
    objId = models.CharField(max_length=200)
    created = models.DateTimeField()
    latitude = models.FloatField()
    longitude = models.FloatField()
    pokemonId = models.IntegerField()
    def __unicode__(self):
        return u'%s' % self.pokemonId

Pokemon_Traker_Site/tracker/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

Pokemon_Traker_Site/pokemon/forms.py
from django.shortcuts import render
from django import forms
from django.forms import ModelForm
from .models import Pokemon
from django.utils.translation import ugettext_lazy as _

class PokemonForm(ModelForm):
    class Meta:
        model = Pokemon
        fields = [
            'objId',
            'created',
            'latitude',
            'longitude',
            'pokemonId'
        ]
        labels = {
            'created': _('time'),
            'latitude': _('latitude'),
            'longitude': _('longitude'),
            'pokemonId': _('No.'),
        }

class DeletePokemon(forms.Form):
    number = forms.IntegerField()

Pokemon_Traker_Site/pokemon/views.py
from django.shortcuts import render
from pokemon.forms import PokemonForm, DeletePokemon
from pokemon.models import Pokemon
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.core.exceptions import ObjectDoesNotExist
from datetime import datetime, timedelta
from django.utils import timezone

# Create your views here.
@csrf_exempt
def markPokemon(request):
    dbName = 'default'
    if request.GET.get('db'):
        dbName = request.GET['db']

    if request.method == "POST":
        form = PokemonForm(request.POST)
        if form.is_valid():
            try:
                pokemon = Pokemon.objects.using(dbName).get(objId = form.cleaned_data['objId'])
                return HttpResponse("Existed")
            except ObjectDoesNotExist:
                new_pokemon = form.save(commit = False)
                new_pokemon.save(using=dbName)
                return HttpResponse("Success")
        else:
            return HttpResponse("Fail")
    else:
        form = PokemonForm()
        return render(request,'pokemon/form.html',{'form':form})

def deletePokemon(request):
    if request.method == 'POST':
        form = DeletePokemon(request.POST)
        if form.is_valid():
            try:
                pokemons = Pokemon.objects.filter(pokemonId = form.cleaned_data['number'])
                pokemons.delete()
                return HttpResponse("Successfully Deleted")
            except:
                return HttpResponse("Error")
    else:
        form = DeletePokemon()
        return render(request,'pokemon/form.html',{'form':form})

def showPokemon(request, pokemonId):
    pokemons = Pokemon.objects.filter(pokemonId = pokemonId).order_by('-created')
    return render(request,'pokemon/table.html',{'pokemons':pokemons})

def deleteTooOldPokemon(request):
    oldTime = timezone.now() - timedelta(hours = 1)
    try:
        oldPokemons = Pokemon.objects.using('hunt').filter(created__lt=(oldTime))
        oldPokemons.delete()
        return HttpResponse("Successfully Deleted Old Pokemons")
    except:
        return HttpResponse("Error")

Pokemon_Traker_Site/tracker/views.py
from django.shortcuts import render
from django.http import HttpResponse
from pokemon.models import Pokemon

# Create your views here.
def tracker(request, pokemonId):
    pokemons = Pokemon.objects.filter(pokemonId = pokemonId)
    return render(request,'tracker/tracker.html',{'pokemons':pokemons, 'pokemonId':pokemonId})

Pokemon_Traker_Site/pokemon/templates/pokemon/form.html
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="https://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.4.5/jquery.datetimepicker.min.css" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.4.5/jquery.datetimepicker.min.js"></script>
<form action="." method="POST">
    {% csrf_token %} {{ form }} 
    <input class="btn btn-primary" type="submit" value="Submit">
</form>
<script>
$(function() {
    $('#id_created').datetimepicker({
        format:'Y-m-d H:i:s',
        });
});
</script>

Pokemon_Traker_Site/pokemon/templates/pokemon/table.html
<h3 style="text-align:center;">{{ pokemons.count }}</h3>
<table>
    <thead>
        <tr>
            <th>id</th>
            <th>time</th>
        </tr>
    </thead>
    <tbody>
        {% for pokemon in pokemons%}
        <tr>
            <td>{{ pokemon.objId }}</td>
            <td>{{ pokemon.created }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

Pokemon_Traker_Site/tracker/templates/tracker/tracker.html
<!DOCTYPE html>
<html>
  <head>
    <title>Pokemon Tracker {{ pokemonId }}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <style>
      html, body, #map {
        margin: 0;
        padding: 0;
        height: 100%;
      }
    </style>
    </head>
  <body>
    <div style="height:100%;width:20%;float:left;">
      <p style="text-align:center;">{{ pokemons.count }}隻</p>
      <table>
        {% for pokemon in pokemons %}
        <tr><td>{{ pokemon.created }}</td></tr>
        {% endfor %}
      </table>
    </div>
    <div id="map"></div>
    <script>
      var map;
      function initialize() {
        map = new google.maps.Map(document.getElementById('map'), {
          zoom: 13,
          center: new google.maps.LatLng(22.635847,120.3145665),
          mapTypeId: 'roadmap',
        });

        function addMarker(feature) {
          var circle = new google.maps.Circle({
            strokeColor: '#FF0000',
            strokeOpacity: 0.8,
            strokeWeight: 1,
            fillColor: '#FF0000',
            fillOpacity: 0.35,
            map: map,
            center: feature.position,
            radius: 50
          });
        }

        var features = [
          {% for pokemon in pokemons %}
          {
            position: new google.maps.LatLng({{ pokemon.latitude }},{{ pokemon.longitude }}),
          }{% if not forloop.last %} , {% endif %}
          {% endfor %}
        ];

        for (var i = 0, feature; feature = features[i]; i++) {
          addMarker(feature);
        }
      }

    </script>
    <script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBlC64rblXkk2fWOFSPOWahgjq_q8B6xjY&callback=initialize">
    </script>
  </body>
</html>